version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - sliit-docker
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  
  backend:
    image: docker-backend:1.0
    container_name: springboot-studentservice-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - sliit-docker
    links:
      - mongodb
    
  frontend:
    image: docker-frontend:1.0
    container_name: reactjs-studentservice-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./frontend:/app
    networks:
      - sliit-docker
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  sliit-docker:
    driver: bridge

volumes:
  mongodb:
  mongodb_config: