apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sliit-app-ingress
  namespace: student-service
  annotations:
     kubernetes.io/ingress.class: nginx
spec:
   rules:
    - host: student-service.naynutty.xyz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: springboot-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-frontend
                port:
                  number: 80
