---
# ===========================================
# MongoDB Deployment
# ===========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret
          volumeMounts:
            - mountPath: /data/db
              name: mongodb
            - mountPath: /data/configdb
              name: mongodb_config
      volumes:
        - name: mongodb
          hostPath:
          # directory location on host
          path: /data
          # this field is optional
          type: DirectoryOrCreate

        - name: mongodb_config
          hostPath:
          # directory location on host
          path: /data
          # this field is optional
          type: DirectoryOrCreate  