apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
            - mountPath: /data/configdb
              name: mongodb-config
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongodb-config
          persistentVolumeClaim:
            claimName: mongodb-pvc