---
# ===========================================
# MongoDB Service (internal only)
# ===========================================
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: student-service
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: ClusterIP