---
# ===========================================
# React Frontend Deployment
# ===========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: student-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: ghcr.io/toakhildevops/student-service/frontend:sha-686a6e02446bed6db149e1719bd1777ec52ec326
          ports:
            - containerPort: 80
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"