name: student-portal CI/CD
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  # ✅ Frontend test & build
  test-frontend:
    if: contains(github.event.head_commit.message, '[skip-frontend]') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect frontend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'

      - name: Skip if no frontend changes
        if: steps.changes.outputs.frontend != 'true'
        run: echo "No frontend changes, skipping" && exit 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: cd frontend && npm install
      - run: cd frontend && npm test -- --passWithNoTests

  build-frontend:
    runs-on: ubuntu-latest
    needs: test-frontend
    if: needs.test-frontend.result == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd frontend && npm install
      - run: cd frontend && NODE_OPTIONS=--openssl-legacy-provider npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

  docker-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    if: needs.build-frontend.result == 'success'
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: build/

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      - name: Build & push frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:sha-${{ github.sha }}    

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:sha-${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'  
      
      - name: push docker image
        if: success() 
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:sha-${{ github.sha }}     

      

  # ✅ Backend build & docker
  test-backend:
    if: contains(github.event.head_commit.message, '[skip-backend]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect backend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'

      - name: Skip if no backend changes
        if: steps.changes.outputs.backend != 'true'
        run: echo "No backend changes, skipping" && exit 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Build & run tests
        run: cd backend && mvn clean verify

  backend-build:
    runs-on: ubuntu-latest
    needs: test-backend
    if: needs.test-backend.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect backend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'

      - name: Skip if no backend changes
        if: steps.changes.outputs.backend != 'true'
        run: echo "No backend changes, skipping" && exit 0

      - name: Build backend with Maven
        run: cd backend && mvn -B package -DskipTests

      - name: Upload backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar

  docker-backend:
    runs-on: ubuntu-latest
    needs: backend-build
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download backend JAR
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: backend/target

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build & push backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:sha-${{ github.sha }}    

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:sha-${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'        
      
      - name: push docker image
        if: success() 
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:sha-${{ github.sha }} 

      

  # ✅ GitOps update
  gitops-update:
    runs-on: ubuntu-latest
    needs: [docker-frontend, docker-backend]
    if: |
      (needs.docker-frontend.result == 'success') || 
      (needs.docker-backend.result == 'success')
    steps:
      - uses: actions/checkout@v4
        with:
          repository: your-org/gitops-repo
          token: ${{ secrets.TOKEN }}
          ref: main

      - name: Update frontend image tag
        if: needs.docker-frontend.result == 'success'
        run: |
          sed -i "s|ghcr.io/.*/frontend:.*|ghcr.io/owner/frontend:sha-${{ github.sha }}|g" k8s/frontend-deployment.yaml

      - name: Update backend image tag
        if: needs.docker-backend.result == 'success'
        run: |
          sed -i "s|ghcr.io/.*/backend:.*|ghcr.io/owner/backend:sha-${{ github.sha }}|g" k8s/backend-deployment.yaml

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add k8s/*.yaml
          git commit -m "Update images to sha-${{ github.sha }}" || echo "No changes"
          git push origin main
